### ISSUE TITLE
Make TwitchBot available in the new app

### ISSUE THREAD

**Issue by dbraillon** [pkshetlie/RagnaCustomsApp#7]
@pkshetlie can you please tell me what is the command the viewers need to write again? What about that '!' character?

**Comment by pkshetlie** [comment]
there are a lot of commands  : 
!rc [song id] -> request a song
!rc cam [id of cam 0 to 9] -> change the spectator camera
!rc queue -> display queue
!rc next -> display next song
!rc shift or !rc done  (only for mederator) -> remove the first song in queue
!rc open  -> open the queue (only for mederator) 
!rc close -> close the queue (only for mederator) 
!rc cancel -> cancel the last song requested by a user
!rc version or  !rc v -> display version od the applciation
!rc how-to por !rc ht -> display a message about how-to use
!rc help -> display available commands

The chatbot prefix  (default :! )  is for everthing that the chatbot say in twitch chat, because without TTS used by streamers read everything without a ! in front of text.
